<?php

namespace ValidationBundle\Entity\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * 
     * @param array $criteria
     * 
     * @return array|NULL
     */
    public function findByUniqueCriteria(array $criteria)
    {
        if($criteria['notification'] == true){
            return $this->findBy($criteria);
        }
        
        return  null;
    }
}
