<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHuvh1ak\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHuvh1ak/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHuvh1ak.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHuvh1ak\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHuvh1ak\appProdProjectContainer(array(
    'container.build_hash' => 'Huvh1ak',
    'container.build_id' => 'd8394ad8',
    'container.build_time' => 1540236750,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHuvh1ak');
