<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBi9m1ts\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBi9m1ts/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBi9m1ts.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBi9m1ts\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBi9m1ts\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bi9m1ts',
    'container.build_id' => 'f7c5e07b',
    'container.build_time' => 1540840935,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBi9m1ts');
